### ISSUE TITLE
文件服务器权限问题

### ISSUE THREAD

**Issue by jpguo520** [wildfirechat/WF-minio#1]
关于使用MinIO服务后，在没有登录的状态下，直接输入下面网址，会将文件桶中的文件信息都会表示出来。有什么设置能避免这一漏洞吗？
```
http://{域名}/media
```
![image](https://user-images.githubusercontent.com/26107242/160543268-6cddadeb-6a01-409f-81e2-e835e446d62b.png)

**Comment by imndx** [comment]
请参考：https://github.com/minio/minio/issues/8402

**Comment by heavyrain2012** [comment]
@jpguo520 你们用的minio服务是不是旧版本的？你什么时候从github上取消来的？

**Comment by jpguo520** [comment]
@heavyrain2012 看日期应该是2020年4月份的版本

**Comment by heavyrain2012** [comment]
太旧了，更新到最新看看

**Comment by jpguo520** [comment]
@heavyrain2012 有详细的升级操作手册吗？我们现在是用docker部署的

**Comment by heavyrain2012** [comment]
我们提供的方式都是直接部署的，docker应该是你们自己封装的镜像。可以找个测试环境按照我们文档上的方法升级测试看看

**Comment by jpguo520** [comment]
是这个升级方法吗
![image](https://user-images.githubusercontent.com/26107242/161362411-caf0806e-31ec-453c-a726-1590e7764216.png)

**Comment by heavyrain2012** [comment]
对的

**Comment by jpguo520** [comment]
好的 我试试~

**Comment by jpguo520** [comment]
升级的时候这几个文件怎么使用
![image](https://user-images.githubusercontent.com/26107242/161363473-af0df9ff-6d9c-44f1-9999-4cdf03aa688c.png)

**Comment by heavyrain2012** [comment]
这是不同平台上的版本，选择正确的平台解压就能得到一个可执行程序minio

**Comment by jpguo520** [comment]
升级完之后有什么明显的标识吗？

**Comment by heavyrain2012** [comment]
没有，你看看你提的问题解决了吗

**Comment by jpguo520** [comment]
最后没有升级minio，参照https://github.com/minio/minio/issues/8402 已经解决本issue问题
