### ISSUE TITLE
minio部署后启动异常

### ISSUE THREAD

**Issue by jpguo520** [wildfirechat/WF-minio#2]
我使用minio_linux_arm64.tar.gz进行minio部署报错能帮看看吗？

![image](https://user-images.githubusercontent.com/26107242/182067071-4d6c6423-1960-44f7-b193-b1fe2fed0322.png)

**Comment by heavyrain2012** [comment]
服务器是x64架构的还是arm64架构的？麻烦把日志发给 support@wildfirechat.cn 我们需要看一下完整的日志

**Comment by jpguo520** [comment]
![image](https://user-images.githubusercontent.com/26107242/182076544-9d739f2b-c889-468f-ad24-af72c01df600.png)
服务器是64位的
这个日志在什么位置？

**Comment by heavyrain2012** [comment]
常见服务器有两种，一种是inter和amd生产的，是x86/x64架构的。另外一种是arm cpu，包括华为麒麟，飞腾等品牌。还有一种就是龙芯的架构。确认一下是哪种

日志就是上面你打码的部分

**Comment by jpguo520** [comment]
我用这个取下来的是minio是可以启动的，说明就是amd64的
wget https://dl.minio.io/server/minio/release/linux-amd64/minio

**Comment by jpguo520** [comment]
>日志就是上面你打码的部分
那个不是我打的码~是执行出来显示的就是这样

**Comment by heavyrain2012** [comment]
那应该就是架构选错了，试试amd架构的是不是都正常吧

**Comment by jpguo520** [comment]
使用amd架构的资源，启动起来了，界面是这样吗？和之前的感觉不一样了~
![image](https://user-images.githubusercontent.com/26107242/182081230-c353fd6e-fe8b-4bb9-bca0-0bc295dbb0b5.png)

**Comment by heavyrain2012** [comment]
是的，我们升级版本了

**Comment by jpguo520** [comment]
好的 完美升级。
